create table if not exists clearing_system_origin_meta_history(
history_date varchar(255) not null,
country_code varchar(255) null,
routing_meta varchar(255) null,
origin varchar(255) null,
audit_flag varchar(255) null,
audit_done char null,
audit_type varchar(255) null,
acted_by varchar(255) null,
audit_source varchar(255) null,
updated_from_source varchar(255) null,
removed_from_source varchar(255) null,
creation_date varchar(255) null,
modified_date varchar(255) null,
entity_state varchar(255) null,
constraint clearing_system_origin_meta_history_pk primary key(history_date));